# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rails Males
email: gauravnarra@gmail.com
description: >
  Just another blog on ruby on rails, ruby, tools to setup/maintain websites.
  What's with males?domain was cheaper & its catchy.
baseurl: ""
url: "http://www.railsmales.com"
twitter_username: gauravnarra
github_username:  gaurav-narra
permalink: /blog-posts/:title

# Build settings
markdown: kramdown
